version: "3.9"
services:
  reactive-app:
    container_name: reactive-app
    build: .
    ports:
      - "8086:8086"
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
      - MONGO_DB=admin
      - MONGO_HOST=my-mongo
      - APP_PORT=27017
    links:
      - mongo-db
  mongo-db:
    container_name: my-mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  myrabbitmq:
    container_name: my-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-data: